### ISSUE TITLE
As a game starts.

### ISSUE THREAD

**Issue by tetris28** [morningpee/mtf#11]
My game lags a lot as the (3...2...1..) countdown and game begins. You brought it to my attention that this was because the game loads the wingraphix for both players everygame (even if they are the exact same players as last game). I feel that preventing these from loading would be able to alleviate a bit of my 5 sec late start to every game. 

Thanks, 
ZeroT

**Comment by TSTdoll** [comment]
@tetris28 cool so now i will do this

**Comment by TSTdoll** [comment]
minimal tetris friends is about removing the things that cause lag. The key
to reducing this lag in particular will be to selectively block the request
for loading the embedded SWF for the 3-2-1 countdown.

**Comment by TSTdoll** [comment]
hi ZeroT, using CSS transforms gives us pretty good hardware acceleration. Will you please test [this version](https://github.com/morningpee/mtf/raw/d098c00ba747498a61e115a876cac56c7265b1c6/Minimal%20Tetris%20Friends.user.js) in Firefox and tell me if it still lags a lot as the game starts?

-mp

other info: relevant commit is d098c00

**Comment by TSTdoll** [comment]
@tetris28, 98d8d7d9e1 includes the option to block winGrafix. In order to block them, click on the "mtf" icon in your browser and make sure "Block winGrafix" is checked.

Try updating in about 45 minutes, as the Chrome version has a publishing delay.
