### ISSUE TITLE
Medals cleared and rank getting set to 1

### ISSUE THREAD

**Issue by TSTdoll** [morningpee/mtf#18]
Spinifex reports that when they use MTF, it removes their medals and ranks them down to rank 1. They report that the "rank 1" is only permanent if they play a game while rank 1. That is, if they log out and uninstall MTF without playing a game, they're back to rank 20.

> Since some months, I used the Minimal Tetris Friends extension for Chrome (not the Tampermonkey version) and it worked well. I encountered some issues after the update though. Somehow, I got ranked down to rank 1. Probably, not related to MTF, but this had some weird consequences: When I was in bronze and silver ranks and used MTF, it told me I was rank 1 (500 points), ignored my tunings (DAS/ARR) and didn't show any score/win screens (lines sent & win counter). I deactived MTF and ranked up to platinum again and those issues were fixed (forgot to check gold). However, I still can't leave any room (clicking the Exit Now button does nothing).

**Comment by morningpee** [comment]
From Okey_Dokey:

> Since some months, I used the Minimal Tetris Friends extension for Chrome (not the Tampermonkey version) and it worked well. I encountered some issues after the update though. Somehow, I got ranked down to rank 1. Probably, not related to MTF, but this had some weird consequences: When I was in bronze and silver ranks and used MTF, it told me I was rank 1 (500 points), ignored my tunings (DAS/ARR) and didn't show any score/win screens (lines sent & win counter). I deactived MTF and ranked up to platinum again and those issues were fixed (forgot to check gold). However, I still can't leave any room (clicking the Exit Now button does nothing).

**Comment by TSTdoll** [comment]
I think cf46145dce fixes this one too. Waiting for a user who had the rank 1 issue to check.

**Comment by TSTdoll** [comment]
Okey_Dokey [confirmed](http://harddrop.com/forums/index.php?showtopic=5597&st=45&p=90553&#entry90553) that their issue is fixed. It is also possible that f0ec2411ba was the fix.
